RetailBackOffice/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "retailoffice"

urlpatterns = [
  path('backedup-data/', views.my_view, name='my_view'),
  path('', views.office_dashboard, name="office_dashboard"),
  path('chatbot', views.chatbot, name="office_chatbot"),
  path('calculator', views.calculator, name="office_calculator"),
  path('advancedreports', views.advanced_reports, name="journals"),
  path('products', views.retrieve_products, name="products"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView
from django.contrib.auth.decorators import user_passes_test
from django.urls import re_path
from django.views.static import serve
from django.conf import settings

def user_is_admin(user):
    return user.is_authenticated and user.is_staff

urlpatterns = [
    #    path('admin/defender/', include('defender.urls')),
    path('api_schema/', user_passes_test(user_is_admin)(
        get_schema_view(
            title='API Schema',
            description='Guide for the REST API'
        )
    ), name='api_schema'),

    path('docs/', user_passes_test(user_is_admin)(
        TemplateView.as_view(
            template_name='docs.html',
            extra_context={'schema_url': 'api_schema'}
        )
    ), name='swagger-ui'),
    path('admin/', admin.site.urls),
    path("",include("website.urls")),
    path("cs/",include("consultant.urls")),
    path("RetailBackOffice/",include("RetailBackOffice.urls"))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
else: urlpatterns += [ re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})]

RetailBackOffice/models.py
from django.db import models

# Create your models here.

RetailBackOffice/views.py
from django.http import JsonResponse 
from django.views.decorators.csrf import csrf_exempt
import json
import os
import datetime 
import time 
from django.shortcuts import render, redirect


# Path to the JSON file
DATA_FILE_PATH = 'office/data.json'

@csrf_exempt
def my_view(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            data["last_updated"] = time.strftime("%D %H:%M")
            pretty_json = json.dumps(data, indent=4, sort_keys=True)
            # print(pretty_json)

            # Save data to JSON file
            with open(DATA_FILE_PATH, 'w') as file:
                file.write(pretty_json)

            return JsonResponse({'status': 'success'})
        
        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Invalid JSON'}, status=400)
    elif request.method == 'GET':
        try:
            if os.path.exists(DATA_FILE_PATH):
                with open(DATA_FILE_PATH, 'r') as file:
                    data = file.read()
                return JsonResponse({'status': 'success', 'data': json.loads(data)}, json_dumps_params={'indent': 4})
            else:
                return JsonResponse({'status': 'error', 'message': 'No data found'}, status=404)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)


def office_dashboard(request):
    return render(request, 'officedashboard.html')


def chatbot(request):
    return render(request, 'plugins/chatbot.html')

def calculator(request):
    return render(request, 'plugins/calculator.html')


def advanced_reports(request):
    return render(request, 'advancedreports.html')


def retrieve_products(request):
    return render(request, 'tables.html')

RetailBackOffice/templates/Components/sidebar2.html
{% load static %}
<div class="sidebar" data-color="white"  data-active-color="danger">
    <div class="logo">
      <a href="https://www.creative-tim.com" class="simple-text logo-mini">
        <div class="logo-image-small">
          <img src="https://www.nextgensell.com/static/assets/img/favicon.png">
        </div>
        <!-- <p>CT</p> -->
      </a>
      <a href="https://www.creative-tim.com" class="simple-text logo-normal">
        NextGenSell
        <!-- <div class="logo-image-big">
          <img src="../assets3/img/logo-big.png">
        </div> -->
      </a>
    </div>
    <div class="sidebar-wrapper" >
      <ul class="nav">
        <li class="active ">
          <a href="{% url "retailoffice:office_dashboard" %}">
            <i class="nc-icon nc-bank"></i>
            <p>Dashboard</p>
          </a>
        </li>
        <li>
          <a href="{% url "retailoffice:products" %}">
            <i class="nc-icon nc-cart-simple"></i>
            <p>Products</p>
          </a>
        </li>
        <li>
          <a href="./map.html">
            <i class="nc-icon nc-app"></i>
            <p>Inventory</p>
          </a>
        </li>
        <li>
          <a href="./notifications.html">
            <i class="nc-icon nc-money-coins"></i>
            <p>Records</p>
          </a>
        </li>
        <li>
          <a href="./notifications.html">
            <i class="nc-icon nc-tile-56"></i>
            <p>Laybuys</p>
          </a>
        </li>
        <li>
          <a href="./notifications.html">
            <i class="nc-icon nc-single-02"></i>
            <p>Customers</p>
          </a>
        </li>
        
        <li>
          <a href="./user.html">
            <i class="nc-icon nc-badge"></i>
            <p>Staff ACCESS</p>
          </a>
        </li>
        <li>
          <a href="./tables.html">
            <i class="nc-icon nc-delivery-fast"></i>
            <p>Suppliers</p>
          </a>
        </li>

        <li class="active-pro">
          <a href="{% url "retailoffice:journals" %}">
            <i class="nc-icon nc-single-copy-04"></i>
            <p>Advanced Reports</p>
          </a>
        </li>
      </ul>
    </div>
  </div>